"""
Adaptive scoring weights module.
Reads accumulated user feedback signals (opens, saves, important flags, ratings) from the DB,
computes per-topic engagement scores, and persists them to config/user_weights.yaml so the
relevance scorer can inject personalized hints into future scoring prompts.
"""

import logging
from datetime import datetime, timezone
from pathlib import Path

import yaml

from techlens.storage.models import Article

logger = logging.getLogger(__name__)

_WEIGHTS_PATH = Path(__file__).parents[3] / "config" / "user_weights.yaml"

# Minimum number of articles in a category before we trust the engagement signal.
_MIN_ARTICLES_FOR_SIGNAL = 2

# Engagement score thresholds for classifying a topic.
_BOOST_THRESHOLD = 0.8    # topic is clearly valued by the user
_PENALTY_THRESHOLD = -0.3  # topic consistently ignored or down-rated


def compute_topic_weights(session) -> dict[str, float]:
    """
    Queries all scored articles in the DB and returns a mapping of
    topic → engagement score (float) for topics with enough data.

    Engagement formula per topic:
        (opens×1 + saves×2 + important×3 + rated_up×2 - rated_down×2) / total_articles
    """
    articles = session.query(Article).filter(Article.score.isnot(None)).all()

    stats: dict[str, dict] = {}
    for a in articles:
        for cat in a.get_categories():
            s = stats.setdefault(cat, {
                "total": 0, "opened": 0, "saved": 0,
                "important": 0, "rated_up": 0, "rated_down": 0,
            })
            s["total"] += 1
            if a.opened_at:        s["opened"] += 1
            if a.is_saved:         s["saved"] += 1
            if a.is_important:     s["important"] += 1
            if a.user_rating == "up":   s["rated_up"] += 1
            if a.user_rating == "down": s["rated_down"] += 1

    weights: dict[str, float] = {}
    for topic, s in stats.items():
        if s["total"] < _MIN_ARTICLES_FOR_SIGNAL:
            continue
        raw = (
            s["opened"] * 1
            + s["saved"] * 2
            + s["important"] * 3
            + s["rated_up"] * 2
            - s["rated_down"] * 2
        ) / s["total"]
        weights[topic] = round(raw, 3)

    return weights


def save_weights(weights: dict[str, float]) -> None:
    """
    Writes computed topic weights to config/user_weights.yaml.
    Splits topics into boosted / penalized / neutral buckets for easy reading.
    """
    boosted = [
        t for t, s in sorted(weights.items(), key=lambda x: -x[1])
        if s >= _BOOST_THRESHOLD
    ]
    penalized = [
        t for t, s in sorted(weights.items(), key=lambda x: x[1])
        if s <= _PENALTY_THRESHOLD
    ]

    data = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "note": "Auto-generated by TechLens feedback loop. Applied on next pipeline run.",
        "boosted": boosted,
        "penalized": penalized,
        "scores": weights,
    }
    with open(_WEIGHTS_PATH, "w") as f:
        yaml.dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    logger.info(
        "Saved adaptive weights: %d boosted, %d penalized topics",
        len(boosted), len(penalized),
    )


def load_weights() -> dict:
    """
    Loads the stored weights file. Returns an empty dict if it does not exist yet
    (i.e., no feedback has been applied yet).
    """
    if not _WEIGHTS_PATH.exists():
        return {}
    with open(_WEIGHTS_PATH) as f:
        return yaml.safe_load(f) or {}


def build_personalization_hint() -> str:
    """
    Reads stored weights and returns a short natural-language hint string
    suitable for appending to the LLM scoring system prompt.
    Returns an empty string if no weights are available.
    """
    weights = load_weights()
    if not weights:
        return ""

    boosted: list[str] = weights.get("boosted", [])[:6]
    penalized: list[str] = weights.get("penalized", [])[:6]

    if not boosted and not penalized:
        return ""

    lines = ["\n\nPersonalization (learned from user reading history):"]
    if boosted:
        lines.append(f"- User actively engages with: {', '.join(boosted)}")
        lines.append("  → Boost scores for articles covering these topics by up to +10 points.")
    if penalized:
        lines.append(f"- User rarely engages with / down-rates: {', '.join(penalized)}")
        lines.append("  → Penalize scores for articles covering only these topics by up to -10 points.")
    lines.append("Apply adjustments only when the topic match is clear.")

    return "\n".join(lines)
